%%%% ProbLog does not support dif/2 %%%%
dif(A,B):- \+(A==B).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

0.2::tagChange(wantedTemp, top).
0.5::tagChange(wantedTemp, medium).
0.3::tagChange(wantedTemp, low).
0.2::tagChange(wantedBright, top).
0.5::tagChange(wantedBright, medium).
0.3::tagChange(wantedBright, low).
0.4::tagChange(cameraActivation, top).
0.4::tagChange(cameraActivation, medium).
0.2::tagChange(cameraActivation, low).
0.5::tagChange(schedule, top).
0.3::tagChange(schedule, medium).
0.2::tagChange(schedule, low).
0.1::tagChange(aiActive, top).
0.1::tagChange(aiActive, medium).
0.8::tagChange(aiActive, low).
0.1::tagChange(networkInput, top).
0.1::tagChange(networkInput, medium).
0.8::tagChange(networkInput, low).
0.1::tagChange(networkOutput, top).
0.1::tagChange(networkOutput, medium).
0.8::tagChange(networkOutput, low).
0.2::tagChange(thermostatTemp, top).
0.3::tagChange(thermostatTemp, medium).
0.5::tagChange(thermostatTemp, low).
0.2::tagChange(lightBright, top).
0.3::tagChange(lightBright, medium).
0.5::tagChange(lightBright, low).
0.7::tagChange(cameraStream, top).
0.2::tagChange(cameraStream, medium).
0.1::tagChange(cameraStream, low).
0.2::tagChange(thermostatStatus, top).
0.6::tagChange(thermostatStatus, medium).
0.2::tagChange(thermostatStatus, low).
0.2::tagChange(lightStatus, top).
0.6::tagChange(lightStatus, medium).
0.2::tagChange(lightStatus, low).
0.7::tagChange(cameraStatus, top).
0.2::tagChange(cameraStatus, medium).
0.1::tagChange(cameraStatus, low).
0.8::tagChange(lockStatus, top).
0.1::tagChange(lockStatus, medium).
0.1::tagChange(lockStatus, low).
0.1::tagChange(lockCommands, top).
0.8::tagChange(lockCommands, medium).
0.1::tagChange(lockCommands, low).
0.3::tagChange(actuationCommands, top).
0.5::tagChange(actuationCommands, medium).
0.2::tagChange(actuationCommands, low).
0.8::tagChange(cameraLive, top).
0.1::tagChange(cameraLive, medium).
0.1::tagChange(cameraLive, low).
0.8::tagChange(credentials, top).
0.1::tagChange(credentials, medium).
0.1::tagChange(credentials, low).
0.1::tagChange(storage, top).
0.2::tagChange(storage, medium).
0.7::tagChange(storage, low).

0.7::tagChange(tlsLibrary, top).
0.2::tagChange(tlsLibrary, medium).
0.1::tagChange(tlsLibrary, low).
0.1::tagChange(openSystem, top).
0.1::tagChange(openSystem, medium).
0.8::tagChange(openSystem, low).
0.1::tagChange(networkDriver, top).
0.1::tagChange(networkDriver, medium).
0.8::tagChange(networkDriver, low).
0.2::tagChange(aiFramework, top).
0.3::tagChange(aiFramework, medium).
0.5::tagChange(aiFramework, low).
0.1::tagChange(sharedDisk, top).
0.1::tagChange(sharedDisk, medium).
0.8::tagChange(sharedDisk, low).
0.1::tagChange(diskDriver, top).
0.1::tagChange(diskDriver, medium).
0.8::tagChange(diskDriver, low).
0.2::tagChange(ligthDriver, top).
0.6::tagChange(ligthDriver, medium).
0.2::tagChange(ligthDriver, low).